apiVersion: v1
kind: PersistentVolume
metadata:
  name: kittens-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath: # The folder name inside the worker node: Project-101-kittens-carousel-static-website-nginx_KUBERNETES. Even if you haven’t created this folder beforehand, it will be automatically created.
    path: "/home/ubuntu/Project-101-kittens-carousel-static-website-nginx_KUBERNETES 